parameters:
    mesalab_admin.controller.crud.class: Mesalab\Bundle\AdminBundle\Controller\CRUD

services:
    mesalab_admin.crud.controller:
        class: %mesalab_admin.controller.crud.class%
#        arguments: [@service_id, "plain_value", %parameter%]
